apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-agent-demo

resources:
  - 00-namespace.yaml
  - nginx-good.yaml
  - nginx-crash.yaml
  - nginx-missing.yaml
  - redis.yaml
